--1. Criar um Banco de dados


CREATE DATABASE LANCHONETE;

--2. Criar a tabela pessoa

CREATE TABLE PESSOA (
	NOME VARCHAR(40),
	CPF_CNPJ VARCHAR(14),
	ENDERECO VARCHAR(30),
	BAIRRO VARCHAR(30),
	CIDADE VARCHAR(30),
	UF VARCHAR(2),
	ATUALIZADO DATETIME,
	CRIADO DATETIME,
)

--3. Selecionar todos os registros da tabela pessoa.

	SELECT * FROM PESSOA;

--4. Limitar colunas que desejo vizualizar

	SELECT NOME, CIDADE FROM PESSOA;

--5. Inserrir um registro na tebela pessoa

	INSERT INTO PESSOA (NOME, CPF_CNPJ, ENDERECO, BAIRRO, CIDADE, UF, ATUALIZADO, CRIADO) VALUES 
	('MATEUS BELTRAME', '14507956734', 'IRINEU BERTANI', 'VILA ESPERANCA', 'PATO BRANCO', 'PR', '2025-25-02 19:40:50', ' 2025-18-02 22:22:50')

	INSERT INTO PESSOA (NOME, CPF_CNPJ, ENDERECO, BAIRRO, CIDADE, UF, ATUALIZADO, CRIADO) VALUES 
	('DIRCEU', '85502978001', 'JOSE FRARON', 'FRARON', 'PATO BRANCO', 'PR', '2025-25-02 19:44:50', '2025-25-02 19:44:50')
-- Padrão Brasileirp PT-BR 18/02/2025
-- Padrão Americano US-EN 2025-18-02 22:22:50

SELECT @@LANGUAGE

--6. Atualizar um determinado registro com condicional

	UPDATE PESSOA SET CIDADE = 'PATO BRANCO' 
WHERE NOME = 'MATEUS BELTRAME';

--7. Adicionar uma coluna em uma tabela existente
ALTER TABLE PESSOA ADD CODIGO BIGINT;

--8. Atualizar codigos na tabela pessoa
UPDATE PESSOA SET CODIGO = 1 WHERE NOME = 'MATEUS BELTRAME';
UPDATE PESSOA SET CODIGO = 2 WHERE NOME = 'DIRCEU';

--9. Deletar registros da tabela PESSOA.
DELETE FROM PESSOA WHERE CODIGO = 1;

--10. Deletar a tabela PESSOA do banco de dados.
DROP TABLE PESSOA;

--11. Consultar por consdicionais
SELECT * FROM PESSOA WHERE CRIADO >= '2025-25-02'

--12. Adicionar a data de aniversario da tabela PESSOA.
ALTER TABLE PESSOA ADD DATA_ANIVERSARIO DATE;

--13. Atualizar a data de aniversario da tabela PESSOA
UPDATE PESSOA SET DATA_ANIVERSARIO = '2007-01-30'
	WHERE NOME = 'MATEUS BELTRAME';

	UPDATE PESSOA SET DATA_ANIVERSARIO = '1979-06-12'
	WHERE NOME = 'DIRCEU';

--14. Realizar consulta na TABELA PESSOA com a função.
SELECT * FROM PESSOA WHERE MONTH(DATA_ANIVERSARIO) = 6;

-- 15 rEALIZAR ALTERAÇÃO DE ELEMENTOS DA COLUNA 
ALTER TABLE PESSOAS ALTER COLUMN TELEFONE VARCHAR(15)
ALTER TABLE PESSOAS ALTER COLUMN SEXO VARCHAR(1)
ALTER TABLE PESSOAS ALTER COLUMN CEP VARCHAR(9)